language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

before_script:
  - cd client-app
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular

  
script:
- ng build client-app
