language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

before_script:
  - cd client-app
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular
  - npm install -g @angular/compiler-cli
  - npm install -g @angular/compiler
  - npm install -g typescript
  
script:
- ng build --prod --base-href https://github.com/Rusty89/SeniorCenterManagmentStudio/tree/develop/client-app
